name: Release Please

on:
  push:
    branches:
      - main

env:
  GIT_CLIFF_CONFIG_URL: https://raw.githubusercontent.com/liblaf/play-with-actions/refs/heads/main/cliff.toml

jobs:
  release-please:
    name: Release Please
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install git-cliff
        uses: taiki-e/install-action@v2
        with:
          tool: git-cliff
      - id: version
        name: Get Bumped Version
        run: |-
          tag="$(git-cliff --bumped-version)"
          version="${tag#'v'}"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - name: Generate Changelog
        run: git-cliff --output CHANGELOG.md
        env:
          GIT_CLIFF_CONFIG_URL: ${{ env.GIT_CLIFF_CONFIG_URL }}
          GIT_CLIFF_OUTPUT: CHANGELOG.md
          GIT_CLIFF_TAG: ${{ steps.version.outputs.tag }}
      - name: Generate PR Body
        run: git-cliff --unreleased
        env:
          GIT_CLIFF__CHANGELOG__HEADER: |-
            ## 🤖 I have created a release _beep boop_
          GIT_CLIFF__CHANGELOG__FOOTER: |-
            ---

            This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).
          GIT_CLIFF_CONFIG_URL: ${{ env.GIT_CLIFF_CONFIG_URL }}
          GIT_CLIFF_OUTPUT: ${{ runner.temp }}/body.md
          GIT_CLIFF_TAG: ${{ steps.version.outputs.tag }}
      - name: Create PR
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "chore(release): ${{ steps.version.outputs.tag }}"
          branch: release-please
          sign-commits: true
          title: "chore(release): ${{ steps.version.outputs.tag }}"
          body-path: "${{ runner.temp }}/body.md"
          labels: |-
            automerge
            release-please
          assignees: ${{ github.repository_owner }}
          reviewers: ${{ github.repository_owner }}
